import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './globals.css';
import { Header } from '@/src/components/header/Header';
import { cn } from '@/src/lib/utils';
import { Providers } from '@/src/components/shared/Providers';

const rubik = Rubik({ subsets: ['latin'], display: 'swap', variable: '--font-rubik' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
    <body className={cn(rubik.className, 'bg-[#561C24] h-screen text-slate-200')}>
    <Providers>
      <Header />
      {children}
    </Providers>
    </body>
    </html>
  );
}
